### ISSUE TITLE
AttributeError: module 'settings_window' has no attribute 'SettingsWindow' on obfuscating multiple files

### ISSUE THREAD

**Issue by TheReshi** [mauricelambert/PyObfuscator#10]
I have added "name1": Name("SettingsWindow", "m4I3yZb4YeUM", False, None) to my names, it also appears in the jsons.

`"names": [{"name": "SettingsWindow", "definition": false, "namespace": null, "obfuscation_name": "UvTAvKoKnOHC"}, {"name": "settings_window", "definition": false, "namespace": null, "obfuscation_name": "mcCqbJjpjqDm"}, {"name": "ArithmeticError", "definition": false, "namespace": null, "obfuscation_name": "PgM9iIkgjogR"}, `...

I obfuscate multiple files with:

```
filenames = ["main",
             "settings_window",
             ...]

for filename in filenames:
    Obfuscator(
        f"{filename}.py",
        f"{output_directory_path}/{filename}.py",
        6,
        {
            "name1": Name("SettingsWindow", "UvTAvKoKnOHC", False, None),
            "name2": Name("settings_window", "mcCqbJjpjqDm", False, None)
        },
        True,
        None,
        "utf-8",
        12,
    ).default_obfuscation()
```

When I start the obfuscated main.py:
```
  File "<string>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 12, in <module>
AttributeError: module 'settings_window' has no attribute 'SettingsWindow'
PS C:\Scripts\ExileMate> 
```

Also tried with Name("SettingsWindow", "m4I3yZb4YeUM", True, None), same. If I put my obfuscated main.py back to the other non-obfuscated files, it works.

What's strange it seems to be able to import the other classes?

```
import sys
from PyQt6.QtWidgets import QApplication, QMessageBox
from PyQt6.QtGui import QFont
import common as com
from main_window import MainWindow
from login_window import LoginWindow
```

SettingsWindow gets imported in main_window so I guess it can import common and main_window?

Is there any way to obfuscate a whole project that consists more files or should I pour everything in a single file?

**Comment by mauricelambert** [comment]
Thanks for opening this issue ! This is a complex and good issue.

Can you reproduce the issue with minimal code ? I will try to reproduce this bug to fix it and i will search methods to obfuscate multiples files easily.

**Comment by mauricelambert** [comment]
Without any update i close this issue.
