### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable on code 'from . import somemodule'

### ISSUE THREAD

**Issue by keewa** [mauricelambert/PyObfuscator#15]
my code files have some relative import like this:

util/
    ├── module1.py
    └── module2.py    from . import module1

  File "...\PyObfuscator.py", line 965, in visit_ImportFrom
    targets, values = self.get_targets_and_value_for_import(
  File "...\PyObfuscator.py", line 671, in get_targets_and_value_for_import
    None if "." not in module else f"myimport({module!r}, {element.name!r})"
TypeError: argument of type 'NoneType' is not iterable

**Comment by mauricelambert** [comment]
Thanks for opening this issue ! Sorry for the long time response, i will check it and i will fix it if i can reproduce the bug.

**Comment by mauricelambert** [comment]
Hi ! I have fixed the bug in the new version (0.1.9). Please upgrade your package (`python3 -m pip install --upgrade PyObfuscator`) and re-try to obfuscate your code.

Thanks for the issue @keewa !
