### ISSUE TITLE
ValueError: Unable to avoid backslash in f-string expression part

### ISSUE THREAD

**Issue by tarekmabdallah91** [mauricelambert/PyObfuscator#3]
Hi @mauricelambert 

Thank you for this tool, 

`raise ValueError(ValueError: Unable to avoid backslash in f-string expression part`

I got this error when tried to obfuscate code contains f-string expressions, when replaced it with `formate()` no Exception was raised

**Comment by mauricelambert** [comment]
Hi @tarekmabdallah91, thanks to opening this issue !

Can you send an example and your python version ? I will fix it.

**Comment by tarekmabdallah91** [comment]
Sure, for example : 

the below code is producing the mentioned Exception  
```
def enter_user_data_for_login(passedValues):
    print(f"{passedValues.user_id}")
```

where this code is not producing this exception

```
def enter_user_data_for_login(passedValues):
    print("{}".format(passedValues.user_id))
```

obfuscating command
`PyObfuscator code.py`

**Comment by mauricelambert** [comment]
I run command with option `-g` set to `1` to get all logs, the last logs are:

```
DEBUG - Name obfuscation for 'print'
DEBUG - Name obfuscation for 'passedValues'
DEBUG - String obfuscation for 'user_id'.
```

The exception is raised after this line: https://github.com/mauricelambert/PyObfuscator/blob/bfae802645e5050f3c60fdb32ef719e7ad0da112/PyObfuscator.py#L855

**Comment by mauricelambert** [comment]
The problem is the end of format string for the AST module:

```
in format string
DEBUG - Name obfuscation for 'passedValues'
not in format string
DEBUG - String obfuscation for 'user_id'.
```

The `user_id` attribute is in the format string but for the AST module at this time the `user_id` is not in the `JoinedStr`. I should found another way to get the end of format string.
