### ISSUE TITLE
AttributeError: module 'x' has no attribute 'y'

### ISSUE THREAD

**Issue by tarekmabdallah91** [mauricelambert/PyObfuscator#4]
Hi, 

I faced this issue today, with different classes

one of them with this line 

`from selenium.webdriver.common.by import By`
`AttributeError: module 'selenium' has no attribute 'by'.`

and for this code as well

```
from ui.user_process_ui.userProcessUI import UserProcessUI
from ui.user_process_ui.userUiMediator import UserUIMediator

output:
  File "<string>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 14, in <module>
AttributeError: module 'ui' has no attribute 'userProcessUI'. Did you mean: 'user_process_ui'?
```
![image](https://github.com/mauricelambert/PyObfuscator/assets/56560184/b7a4dd92-2a8e-4922-8ed2-2a45c440a73a)

obfuscator.py 
```
from PyObfuscator import Obfuscator
Obfuscator(
    r"mainUI.py",
    r"obfu_mainUI.py",
    6,
    deobfuscate=True,
    encoding="utf-8",
    names_size=8,
).default_obfuscation()

```

**Comment by mauricelambert** [comment]
Thanks for opening the issue, i found the bug:

First i get the code for the import line (obfuscation level 1), this line raise the exception reported:

```python
XjKrgUnFvsqa, = (jYC6cvTiQU7E(jYC6cvTiQU7E(Sv7jeJw23tW7('selenium.webdriver.common.by', 'By'), 'by'), 'By'),)
```

In second time i try the following line:

```python
XjKrgUnFvsqa, = (jYC6cvTiQU7E(jYC6cvTiQU7E(jYC6cvTiQU7E(jYC6cvTiQU7E(Sv7jeJw23tW7('selenium.webdriver.common.by', 'By'), "webdriver"), "common"), 'by'), 'By'),)
```

This line is working good. The problem is: i *get attribute* for the last module not for all, i will fix it.

**Comment by mauricelambert** [comment]
The bug is here:

https://github.com/mauricelambert/PyObfuscator/blob/38e96cd0d1b86f3990316fe2c95cadc9dac5e158/PyObfuscator.py#L678
