### ISSUE TITLE
Pyinstaller issue

### ISSUE THREAD

**Issue by Arsenicss** [mauricelambert/PyObfuscator#7]
Where should I set those variables, I've tried to add them in a couple of my script files but running them again after packaging gives me an error
```
NameError: name 'copyright' is not defined
[3432] Failed to execute script 'main' due to unhandled exception!
```

**Comment by tarekmabdallah91** [comment]
@mauricelambert 

I am facing this issue as well, please support to fix it

**Comment by mauricelambert** [comment]
Thanks for opening this issue !

I known this issue and i have written a soluce in the documentation since the first version, please read the [README - pyinstaller](https://github.com/mauricelambert/PyObfuscator#pyinstaller).

**Comment by mauricelambert** [comment]
@Arsenicss, @tarekmabdallah91 please try the solution [described in the documentation](https://github.com/mauricelambert/PyObfuscator#pyinstaller) and explain me if you have any problem with this solution.

**Comment by mauricelambert** [comment]
To fix this bug you should copy and paste the following code at the start of the file:

```python
copyright="""Copyright (c) 2001-2021 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved."""
credits="""    Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information."""
help="Type help() for interactive help, or help(object) for help about object."
quit="Use quit() or Ctrl-Z plus Return to exit"
license="Type license() to see the full license text"
__cached__=""
```

**Comment by Arsenicss** [comment]
@mauricelambert These variables should be added to the obfuscated file. I began to understand that in order to add them to the source file, it has been solved now, but a variable named `exit` also needs to be added.
