### ISSUE TITLE
AttributeError: 'Thread' object has no attribute 'yzFDQHyn'

### ISSUE THREAD

**Issue by hejun041** [mauricelambert/PyObfuscator#8]
threading.Thread(target=start, args=(phone, run_ua))
加密等级1-6都一样

**Comment by mauricelambert** [comment]
Thanks for opening this issue. Please speak English and write the minimum code to reproduce this bug.

**Comment by hejun041** [comment]
> 感谢您打开此问题。请说英语并编写最少的代码来重现此错误。

`p = threading.Thread(target=start, args=(phone, run_ua))`
I use a thread and then I got this error
`AttributeError: 'Thread' object has no attribute 'yzFDQHyn'`

**Comment by mauricelambert** [comment]
> > 感谢您打开此问题。请说英语并编写最少的代码来重现此错误。
> 
> `p = threading.Thread(target=start, args=(phone, run_ua))` I use a thread and then I got this error `AttributeError: 'Thread' object has no attribute 'yzFDQHyn'`

This is not a minimum code to reproduce the bug. I don't know how you have imported `threading` (probably with `import threading` but i guess), `phone` and `run_ua` is not defined.

I don't want to read your personal code but i need a minimal code to reproduce this issue to fix it... To reproduce this issue i need code that works well without obfuscation and doesn't work with my obfuscation.

**Comment by mauricelambert** [comment]
I write a simple code with `threading` and that is working good for me without and with obfuscation, i really need a minimum code to reproduce this bug to fix it:

```python
import threading

t = threading.Thread(target=print, args=("abc",))
t.start()
```

![Screenshot 2023-10-08 141617](https://github.com/mauricelambert/PyObfuscator/assets/50479118/26ed820a-896e-4259-844b-f402b68e019a)

**Comment by hejun041** [comment]
Thanks for your careful guidance, this is a great library
I found the cause of this bug
I defind a function that named `start`
Its naming is the same as the start method of thread
```
import threading
def start:
    print("this is a log")

t = threading.Thread(target=start, args=("abc",))
t.start()
```
like this
I change the name ,then it works fine
Thanks again

**Comment by mauricelambert** [comment]
Thanks ! This a good issue, i will fix it in few days !

**Comment by mauricelambert** [comment]
This code is obfuscated like this at level 1:

```python
import threading
def start():
    print("this is a log")

t = threading.Thread(target=start, args=("abc",))
t.start()
```

```python
def lVAQxX0Gl37e():
    I4GGiRL2mDgB('this is a log')
pJHrIVbkjssC = jxz4s9ZcHv0D.Thread(target=lVAQxX0Gl37e, args=('abc',))
CnMVJ9WiWXON(pJHrIVbkjssC, 'lVAQxX0Gl37e')()
```

There is an error with the attribute name having the same name as a function name.

**Comment by mauricelambert** [comment]
This bug come from: https://github.com/mauricelambert/PyObfuscator/blob/77aca058cb7115cdf98b24b36ebf02e7b6c75150/PyObfuscator.py#L1242

```python
    def visit_Attribute(self, attribute: Attribute) -> Attribute:
        """
        This function obfuscate attribute name.

        attribute: Attribute object
        return an Attribute object with obfuscate name
        """

        if (name := self.default_names.get(attribute.attr)) is not None:
            debug(f"Change attribute: {attribute.attr}")
            if name.is_defined:
                attribute.attr = name.obfuscation
```

There is no check for source of attribute name, that cause this bug.

**Comment by mauricelambert** [comment]
This bug is very difficult to resolve because the source of the attribute is very difficult to identify statically, the only way to do it without any bug is a dynamic check but this is not possible in this library because this library should not run code to obfuscate it. I'll look into the best way to solve it but I probably need some help.
