### ISSUE TITLE
wrong obfuscation for "except Exception as e:"

### ISSUE THREAD

**Issue by miketokio** [mauricelambert/PyObfuscator#9]
Obfuscated with python script by calling:

`Obfuscator('script.py', 'script_obfu.py', level=1, names_size=9).default_obfuscation()`

Original code

```
except Exception as e:
    print(str(e))
```

Obfuscated code

```
except kDYQWVZjZ as e:
    opB6FGZA9(S4BNcgEoB(lb28boSG9))
```
So, it is still unobfuscated in first line like 'as e:' but in second line, where 'e' is accessed, it is obfuscated.

**Comment by miketokio** [comment]
python is 3.10.12

**Comment by mauricelambert** [comment]
Thanks for opening this issue, sorry for the long response time. I fix it now.

**Comment by mauricelambert** [comment]
In the except syntax there is no `Name` ast object used for the variable, only a `name` attribute.

I have added a new method to fix this bug. As little demonstration, i obfuscate the following code:

```python
try:
    abc
except:
    pass

try:
    abc
except Exception as e:
    e
```

Obfuscation:

```python
try:
    JpObHSDtTEPg
except:
    pass
try:
    JpObHSDtTEPg
except IUtJMf6n2BkI as wBuZ9likWKkK:
    wBuZ9likWKkK
```
